# Generated by Django 5.0.6 on 2024-05-23 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250)),
                ('short_name', models.CharField(max_length=10)),
                ('type_educational', models.CharField(max_length=3)),
                ('image', models.CharField(max_length=2083)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('website', models.CharField(max_length=100)),
                ('main_advantages', models.TextField()),
                ('budget_places', models.IntegerField()),
                ('avg_certificate_score', models.FloatField()),
                ('num_specialties', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('working_hours', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('educational_institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akudapostupat.educationalinstitution')),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('qualification', models.CharField(max_length=250)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('budget_places', models.IntegerField()),
                ('duration', models.CharField(max_length=50)),
                ('educational_institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akudapostupat.educationalinstitution')),
            ],
        ),
    ]
