# Generated by Django 5.0.6 on 2024-06-07 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akudapostupat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('list_of_name_of_university', models.TextField(blank=True, null=True)),
                ('invite_after_class', models.TextField(blank=True, null=True)),
                ('invite_after_exams', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Категория ВУЗов',
                'verbose_name_plural': 'Категории ВУЗов',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_url', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('time_table', models.TextField(blank=True, null=True)),
                ('number', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Specialities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('qualification', models.TextField(blank=True, null=True)),
                ('cost', models.IntegerField(blank=True, null=True)),
                ('places', models.IntegerField(blank=True, null=True)),
                ('years_of_studying', models.IntegerField(blank=True, null=True)),
                ('months_of_studying', models.IntegerField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Специальность',
                'verbose_name_plural': 'Специальности',
            },
        ),
        migrations.RemoveField(
            model_name='specialty',
            name='educational_institution',
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('shortName', models.CharField(max_length=100)),
                ('list_of_pluses', models.JSONField(blank=True, default=list)),
                ('places', models.IntegerField(default=0)),
                ('score', models.FloatField(default=0)),
                ('amount_of_specialities', models.IntegerField(default=0)),
                ('list_of_name_of_university', models.TextField(blank=True, null=True)),
                ('invite_after_class', models.TextField(blank=True, null=True)),
                ('invite_after_exams', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('contacts', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='akudapostupat.contacts')),
                ('specialities', models.ManyToManyField(blank=True, related_name='specialities', to='akudapostupat.specialities')),
            ],
            options={
                'verbose_name': 'Категория ВУЗов',
                'verbose_name_plural': 'Категории ВУЗов',
            },
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='EducationalInstitution',
        ),
        migrations.DeleteModel(
            name='Specialty',
        ),
    ]
