# Generated by Django 5.0.6 on 2024-06-07 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akudapostupat', '0004_alter_types_options_university_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type_of_university', to='akudapostupat.category'),
        ),
        migrations.DeleteModel(
            name='Types',
        ),
    ]
