# Generated by Django 5.0.6 on 2024-06-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akudapostupat', '0007_remove_university_invite_after_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='university_images/'),
        ),
    ]
